### ISSUE TITLE
Create ER diagram

### ISSUE THREAD

**Issue by okuzmeniuk** [PMi-33-2024-2025/InventoryManagement#10]

**Comment by romanvcode** [comment]
![ERD drawio](https://github.com/user-attachments/assets/695d7d91-64a0-4d20-b4f1-2a9d86059cb5)

**Comment by romanvcode** [comment]
![ERD drawio](https://github.com/user-attachments/assets/f6e49e08-b2ef-4435-93dd-5a6c0ab65bda)
