### ISSUE TITLE
Describe functional requirements

### ISSUE THREAD

**Issue by okuzmeniuk** [PMi-33-2024-2025/InventoryManagement#5]
Функціональні вимоги включають опис вікон програми, що на них буде розміщено і яку вони будуть мати функціональність, переходи між вікнами, а також треба описати типових юзерів аплікації, по ролях, якщо будуть.

**Comment by hrytsykvl** [comment]
### Опис типових користувачів

1. **Адміністратор**
    - Повний доступ до усіх функцій аплікації.
    - Може створювати, редагувати та видаляти записи інвентарю.
    - Можливість переглядати зареєстровані акаунти, видаляти їх.
    - Переглядати історію змін в інвентарі.
2. **Зареєстрований користувач**
    - Доступ до додавання нових одиниць інвентарю та їх редагування.
    - Може переглядати та фільтрувати інвентар.
    - Можливість переглядати історію змін
3. **Незареєстрований користувач**
    - Доступ до перегляду наявного товару.
 ---
### Основні вікна та їх функціональність
1. **Список інвентарю**
    - Відображає список усіх одиниць інвентарю з можливістю фільтрації та пошуку за параметрами (назва, категорія, постачальник, кількість на складі тощо).
    - Можливість додавання нової одиниці інвентарю (доступно для менеджерів та адміністраторів).
    - Можливість редагування інформації про одиницю інвентарю (доступно для менеджерів та адміністраторів).
    - Можливість видалення одиниць інвентарю (доступно для менеджерів та адміністраторів).
    - Можливість перегляду детальної інформації про одиницю інвентарю:
        - Назва, код товару.
        - Кількість на складі.
        - Опис.
        - Постачальник.
        - Дата останнього оновлення.
     - Перехід до інших розділів:
         - При додаванні, редагуванні товарів з'являється нове вікно.
 2. **Вікно додавання/редагування одиниці інвентарю**
    - Містить форму для введення або редагування інформації про товар:
        - Назва.
        - Категорія.
        - Кількість.
        - Опис.
        - Постачальник.
        - Вартість.
        - Номер товару.
    - Відбувається збереження або оновлення запису в базі даних.
    - Здійснюється валідація усіх полів.
    - Можливість додати нову категорію або постачальника, якщо їх немає у системі.
    - Перехід до інших розділів:
        - Повернення на сторінку інвентарю.
 3. **Вікно управління користувачами (лише для Адміністратора)**
    - Відображає список усіх зареєстрованих користувачів.
    - Доступ для видалення користувача.
    - Перехід до інших розділів:
        - Перехід на сторінку інвентарю.
4. **Вікно входу та реєстрації**
    - Користувачі можуть увійти або зареєструватись у систему.
    - Логін/лог-аут користувача.
    - Зміна пароля.
    - Переходи між вікнами:
        - Користувач після входу потрапляє вікно інвентарю.
