### ISSUE TITLE
Describe non-functional requirements

### ISSUE THREAD

**Issue by okuzmeniuk** [PMi-33-2024-2025/InventoryManagement#6]
Нефункціональні вимоги - це загальні характеристики програми: мова інтерфейсу, вимоги до ПЗ для запуску програми, яка база даних, вимоги по безпеці

**Comment by hrytsykvl** [comment]
###  Нефункціональні вимоги
- Програма повинна підтримувати роботу з базою даних, яка може обробити громістку кількість записів інвентарю, без суттєвого зниження швидкодії.
- Обрана СКБД: Microsoft SQL Server.
- Мова інтерфейсу: Українська.
- Операційна система: Windows 10/11 (x64)



- Аутентифікація та авторизація:
    - Вхід до системи має бути захищеним за допомогою паролів.
- Розмежування доступу:
    - Кожен користувач має мати доступ лише до тих функцій, що відповідають його ролі.
- Резервне копіювання:
    - Необхідне автоматичне регулярне резервне копіювання бази даних.
    - Дані повинні бути відновлюваними з резервних копій без втрати інформації.
- Журнал дій:
    - Всі зміни в інвентарі повинні бути збережені з інформацією про те, хто, коли і які дії виконував.
