### ISSUE TITLE
Draw usecase diagrams

### ISSUE THREAD

**Issue by okuzmeniuk** [PMi-33-2024-2025/InventoryManagement#7]
Намалювати usecase діаграми, що може робити кожен тип користувача з вашою програмою

**Comment by romanvcode** [comment]
![Image](https://github.com/user-attachments/assets/92bb3d3b-c947-4981-9512-f4bb7154c25d)

**Comment by romanvcode** [comment]
![Image](https://github.com/user-attachments/assets/87a3822e-5435-48ba-afa2-12707029d097)

**Comment by romanvcode** [comment]
![UseCases drawio](https://github.com/user-attachments/assets/4fd8460e-ca5f-4752-b302-49cc82dcdb2d)

**Comment by romanvcode** [comment]
![UseCases drawio](https://github.com/user-attachments/assets/d6fa2af5-e76a-475a-b798-f8532a0351b6)

**Comment by romanvcode** [comment]
![UseCases drawio](https://github.com/user-attachments/assets/3d25b355-00ea-45bf-a394-5c95007e6a1b)
